engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 700324494c75296f38cd27a1e79da2fb
    config:
      languages:
      - python
ratings:
   paths:
   - "**.py"
exclude_paths:
- "third-party/**"
- "acquisitions/migrations/*"
