# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_owner', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('rfq_id', models.IntegerField()),
                ('period_of_performance', models.DateField()),
                ('dollars', models.IntegerField()),
                ('set_aside_status', models.CharField(max_length=100)),
                ('amount_of_competition', models.IntegerField()),
                ('contract_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('naics', models.IntegerField()),
                ('competition_strategy', models.CharField(max_length=100)),
                ('procurement_method', models.CharField(max_length=100)),
                ('award_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
            options={
                'ordering': ('rfq_id',),
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractingOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractingOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contracting_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.ContractingOffice')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='COR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acquisition', models.ManyToManyField(to='acquisitions.Acquisition')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Acquisition')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subagency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Agency')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='acquisition',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Agency'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='contracting_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.ContractingOffice'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='contracting_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.ContractingOfficer'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='contracting_officer_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.COR'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='subagency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Subagency'),
        ),
    ]
