# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Releases',
            new_name='Release',
        ),
    ]
