# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('acquisitions', '0003_auto_20160531_1702'), ('acquisitions', '0004_acquisition_award_status'), ('acquisitions', '0005_auto_20160531_1952'), ('acquisitions', '0006_auto_20160531_1956'), ('acquisitions', '0007_auto_20160531_2006')]

    dependencies = [
        ('acquisitions', '0002_auto_20160527_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='amount_of_competition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='competition_strategy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contracting_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.ContractingOffice'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contracting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.ContractingOfficer'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contracting_officer_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.COR'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='dollars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='naics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='period_of_performance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='product_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='rfq_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='set_aside_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='award_status',
            field=models.CharField(choices=[('1) 18F - Qual', '1) 18F - Qual'), ('2) OGC - Qual', '2) OGC - Qual'), ('3) OGP - Qual', '3) OGP - Qual'), ('4) 18F - Agreement Scoping', '4) 18F - Agreement Scoping'), ('5) 18F - Agreement Approval', '5) 18F - Agreement Approval'), ('6) OGC - Agreement Approval', '6) OGC - Agreement Approval'), ('7) 18F - RFQ Scoping', '7) 18F - RFQ Scoping'), ('8) OGC - RFQ Scoping', '8) OGC - RFQ Scoping'), ('9) OGP - RFQ Scoping', '9) OGP - RFQ Scoping'), ('10) 18F - RFQ Ready', '10) 18F - RFQ Ready'), ('11) 18F - RFQ on Street', '11) 18F - RFQ on Street'), ('12) 18F - Eval', '12) 18F - Eval'), ('13) OGC - Eval', '13) OGC - Eval'), ('14) OGP - Eval', '14) OGP - Eval'), ('15) 18F - Award', '15) 18F - Award'), ('16) OGC - Award', '16) OGC - Award'), ('17) OGP - Award', '17) OGP - Award'), ('18) 18F - Post-award', '18) 18F - Post-award')], default='18F - Qual', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='acquisition',
            options={},
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='award_status',
            field=models.IntegerField(choices=[(1, '18F - Qual'), (2, 'OGC - Qual'), (3, 'OGP - Qual'), (4, '18F - Agreement Scoping'), (5, '18F - Agreement Approval'), (6, 'OGC - Agreement Approval'), (7, '18F - RFQ Scoping'), (8, 'OGC - RFQ Scoping'), (9, 'OGP - RFQ Scoping'), (10, ' 18F - RFQ Ready'), (11, ' 18F - RFQ on Street'), (12, ' 18F - Eval'), (13, ' OGC - Eval'), (14, ' OGP - Eval'), (15, ' 18F - Award'), (16, ' OGC - Award'), (17, ' OGP - Award'), (18, ' 18F - Post-award')], default=0),
        ),
    ]
