# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0003_auto_20160531_1702_squashed_0007_auto_20160531_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('duns', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='DUNS number must be 9 digits', regex='^\\d{9}$')])),
            ],
        ),
        migrations.AddField(
            model_name='acquisition',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Vendor'),
        ),
    ]
