# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0004_auto_20160606_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
