# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0005_auto_20160607_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='contractingoffice',
            options={'verbose_name': 'Contracting Office', 'verbose_name_plural': 'Contracting Offices'},
        ),
        migrations.AlterModelOptions(
            name='contractingofficer',
            options={'ordering': ('name',), 'verbose_name': 'Contracting Officer', 'verbose_name_plural': 'Contracting Officers'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'ordering': ('name',), 'verbose_name': 'Contracting Officer Representative', 'verbose_name_plural': 'Contracting Officer Representatives'},
        ),
        migrations.AlterModelOptions(
            name='subagency',
            options={'ordering': ('name',), 'verbose_name_plural': 'Subagencies'},
        ),
    ]
