# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0007_auto_20160617_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(editable=False, null=True)),
                ('is_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acquisitions.AwardStatus')),
            ],
            options={
                'verbose_name_plural': 'Award Statuses',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='award_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.AwardStatus'),
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Track'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Track'),
            preserve_default=False,
        ),
    ]
