# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0007_auto_20160617_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Award Statuses',
            },
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='award_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.AwardStatus'),
        ),
    ]
