# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0008_auto_20160619_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='External', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='is_before',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.AwardStatus'),
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='ordering',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Track'),
            preserve_default=False,
        ),
    ]
