# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0009_auto_20160621_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardstatus',
            name='is_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.AwardStatus'),
        ),
    ]
