# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0008_role_squashed_0010_auto_20160622_0918'),
        ('acquisitions', '0009_auto_20160624_1622'),
    ]

    operations = [
    ]
