# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0010_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='awardstatus',
            old_name='actor',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='time_allotment',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='awardstatus',
            name='wip_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
