# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0011_auto_20160628_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('order',)},
        ),
    ]
