# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0011_auto_20160627_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Acquisition')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.AwardStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
