# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0011_auto_20160628_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
