# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0012_auto_20160628_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Agency'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='roles',
            field=models.ManyToManyField(blank=True, to='acquisitions.Role'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='stage',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Stage'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='step',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='track', chained_model_field='track', on_delete=django.db.models.deletion.CASCADE, to='acquisitions.Step'),
        ),
    ]
