# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0013_auto_20160628_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='stage',
        ),
    ]
