# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0014_auto_20160628_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
