# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0016_steptrackthroughmodel_wip_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={},
        ),
        migrations.RemoveField(
            model_name='step',
            name='order',
        ),
    ]
