# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0018_stage_wip_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='cgac_agency_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='omb_agency_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='omb_bureau_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='treasury_agency_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='naics',
            field=models.IntegerField(blank=True, null=True, verbose_name='NAICS Code'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='rfq_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='RFQ ID'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='wip_limit',
            field=models.IntegerField(default=0, verbose_name='WIP Limit'),
        ),
        migrations.AlterField(
            model_name='steptrackthroughmodel',
            name='wip_limit',
            field=models.IntegerField(default=0, verbose_name='WIP Limit'),
        ),
    ]
