# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0019_auto_20160712_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steptrackthroughmodel',
            unique_together=set([('track', 'step')]),
        ),
    ]
