# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0021_auto_20160712_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('name',), 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('steptrackthroughmodel__order',)},
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='competition_strategy',
            field=models.CharField(blank=True, choices=[('A/E Procedures', 'A/E Procedures'), ('Competed under SAP', 'Competed under SAP'), ('Competitive Delivery Order Fair Opportunity Provided', 'Competitive Delivery Order Fair Opportunity Provided'), ('Competitive Schedule Buy', 'Competitive Schedule Buy'), ('Fair Opportunity', 'Fair Opportunity'), ('Follow On to Competed Action (FAR 6.302-1)', 'Follow On to Competed Action (FAR 6.302-1)'), ('Follow On to Competed Action', 'Follow On to Competed Action'), ('Full and Open after exclusion of sources (competitive small business             set-asides, competitive 8a)', 'Full and Open after exclusion of sources (competitive small             business set-asides, competitive 8a)'), ('Full and Open Competition Unrestricted', 'Full and Open Competition Unrestricted'), ('Full and Open Competition', 'Full and Open Competition'), ('Limited Sources FSS Order', 'Limited Sources FSS Order'), ('Limited Sources', 'Limited Sources'), ('Non-Competitive Delivery Order', 'Non-Competitive Delivery Order'), ('Not Available for Competition (e.g., 8a sole source, HUBZone &             SDVOSB sole source, Ability One, all > SAT)', 'Not Available for Competition (e.g., 8a sole source, HUBZone &             SDVOSB sole source, Ability One, all > SAT)'), ('Not Competed (e.g., sole source, urgency, etc., all > SAT)', 'Not Competed (e.g., sole source, urgency, etc., all > SAT)'), ('Not Competed under SAP (e.g., Urgent, Sole source, Logical             Follow-On, 8a, HUBZone & SDVOSB sole source, all < SAT)', 'Not Competed under SAP (e.g., Urgent, Sole source, Logical             Follow-On, 8a, HUBZone & SDVOSB sole source, all < SAT)'), ('Partial Small Business Set-Aside', 'Partial Small Business Set-Aside'), ('Set-Aside', 'Set-Aside'), ('Sole Source', 'Sole Source')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Cost No Fee', 'Cost No Fee'), ('Cost Plus Award Fee', 'Cost Plus Award Fee'), ('Cost Plus Fixed Fee', 'Cost Plus Fixed Fee'), ('Cost Plus Incentive Fee', 'Cost Plus Incentive Fee'), ('Cost Sharing', 'Cost Sharing'), ('Fixed Price Award Fee', 'Fixed Price Award Fee'), ('Fixed Price Incentive', 'Fixed Price Incentive'), ('Fixed Price Labor Hours', 'Fixed Price Labor Hours'), ('Fixed Price Level of Effort', 'Fixed Price Level of Effort'), ('Fixed Price Time and Materials', 'Fixed Price Time and Materials'), ('Fixed Price with Economic Price Adjustment', 'Fixed Price with Economic Price Adjustment'), ('Fixed Price', 'Fixed Price'), ('Interagency Agreement', 'Interagency Agreement'), ('Labor Hours and Time and Materials', 'Labor Hours and Time and Materials'), ('Labor Hours', 'Labor Hours'), ('Order Dependent', 'Order Dependent'), ('Time and Materials', 'Time and Materials')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('Ability One', 'Ability One'), ('Basic Ordering Agreement', 'Basic Ordering Agreement'), ('Blanket Purchase Agreement-BPA', 'Blanket Purchase Agreement-BPA'), ('BPA Call', 'BPA Call'), ('Call Order under GSA Schedules BPA', 'Call Order under GSA Schedules BPA'), ('Commercial Item Contract', 'Commercial Item Contract'), ('Contract modification', 'Contract modification'), ('Contract', 'Contract'), ('Definitive Contract other than IDV', 'Definitive Contract other than IDV'), ('Definitive Contract', 'Definitive Contract'), ('Government-wide Agency Contract-GWAC', 'Government-wide Agency Contract-GWAC'), ('GSA Schedule Contract', 'GSA Schedule Contract'), ('GSA Schedule', 'GSA Schedule'), ('GSA Schedules Program BPA', 'GSA Schedules Program BPA'), ('Indefinite Delivery Indefinite Quantity-IDIQ', 'Indefinite Delivery Indefinite Quantity-IDIQ'), ('Indefinite Delivery Vehicle (IDV)', 'Indefinite Delivery Vehicle (IDV)'), ('Indefinite Delivery Vehicle Base Contract', 'Indefinite Delivery Vehicle Base Contract'), ('Multi-Agency Contract', 'Multi-Agency Contract'), ('Negotiated', 'Negotiated'), ('Order under GSA Federal Supply Schedules Program', 'Order under GSA Federal Supply Schedules Program'), ('Order under GSA Schedules Program BPA', 'Order under GSA Schedules Program BPA'), ('Order under GSA Schedules Program', 'Order under GSA Schedules Program'), ('Order under IDV', 'Order under IDV'), ('Purchase Order', 'Purchase Order'), ('Sealed Bid', 'Sealed Bid')], max_length=100, null=True),
        ),
    ]
