# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0021_auto_20160712_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
